name: build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 19 * * *'
env:
  DOCKER_HUB_REPO: v03413/acg-faka-assets-cdn
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_HUB_REPO }}
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Generate Docker Tag
        run: |
          export TZ='Asia/Shanghai'
          echo "DOCKER_TAG=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_HUB_REPO }}:latest
            ${{ env.DOCKER_HUB_REPO }}:nightly-${{ env.DOCKER_TAG }} 
